// ═══════════════════════════════════════════════════════════════════════════════
// src/TelemetryModule.jsx — v4.2
// Live mode extracted to live/LiveMode.jsx (FPV camera, 40-ch graphs, all panels)
// Analyze mode: 7 workspaces, 31 charts
// ═══════════════════════════════════════════════════════════════════════════════

import React, { useState, useMemo } from "react";
import {
  LineChart, Line, AreaChart, Area, BarChart, Bar, ScatterChart, Scatter,
  ComposedChart, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, ReferenceLine, ReferenceArea, Cell, Legend,
} from "recharts";
import { C, GL, GS, TT, AX } from "./theme.js";
import { Sec, GC, Pill, FadeSlide } from "./components.jsx";
import {
  gLoadTransfer, gLapDelta, gSlipEnergy, gFrictionSatHist,
  gFreqResponse, gDamperHist, gRideHeightHist, gRollCenterMig, gPSDOverlay,
  gEKFInnovation, gPacejkaDrift, gGripUtil, gDriverInputs,
  gHorizonTraj, gWaveletCoeffs, gALSlack, gControlEffort,
  gHamiltonianEnergy, gDissipationBreakdown, gUndersteerGrad,
  gYawPhaseLag, gFidelitySpider,
} from "./data.js";
import { TubeTrackMap } from "./canvas";
import LiveMode from "./live/LiveMode.jsx";

// ═════════════════════════════════════════════════════════════════════════════
// ANALYZE MODE — 7 WORKSPACES, 31 CHARTS
// ═════════════════════════════════════════════════════════════════════════════
const AZ_TABS=[{key:"overlay",label:"Overlay & Delta"},{key:"tubes",label:"Tubes & Thermal"},{key:"spatial",label:"Spatial"},{key:"frequency",label:"Frequency"},{key:"fidelity",label:"Fidelity"},{key:"contact",label:"Contact & Energy"},{key:"ai",label:"AI Diagnostics"}];

function AnalyzeMode({track,tireTemps,thermal5,tubes,energy,alData}){
  const[ws,setWs]=useState("overlay");
  const lapDelta=useMemo(()=>track?gLapDelta(track):[],[track]);
  const gripUtil=useMemo(()=>track?gGripUtil(track):[],[track]);
  const loadTrans=useMemo(()=>track?gLoadTransfer(track):[],[track]);
  const slipE=useMemo(()=>track?gSlipEnergy(track):[],[track]);
  const fricSat=useMemo(()=>track?gFrictionSatHist(track):[],[track]);
  const understeer=useMemo(()=>track?gUndersteerGrad(track):[],[track]);
  const yawLag=useMemo(()=>track?gYawPhaseLag(track):[],[track]);
  const ctrlEff=useMemo(()=>track?gControlEffort(track):[],[track]);
  const alSlack=useMemo(()=>track?gALSlack(track):[],[track]);
  const hamilE=useMemo(()=>track?gHamiltonianEnergy(track):[],[track]);
  const driverIn=useMemo(()=>track?gDriverInputs(track):[],[track]);
  const horizon=useMemo(()=>gHorizonTraj(),[]);
  const wavCoeffs=useMemo(()=>gWaveletCoeffs(),[]);
  const ekf=useMemo(()=>gEKFInnovation(),[]);const pacDrift=useMemo(()=>gPacejkaDrift(),[]);
  const freqResp=useMemo(()=>gFreqResponse(),[]);const damperH=useMemo(()=>gDamperHist(),[]);
  const rcMig=useMemo(()=>gRollCenterMig(),[]);const psd=useMemo(()=>gPSDOverlay(),[]);
  const rideH=useMemo(()=>gRideHeightHist(),[]);const fidelity=useMemo(()=>gFidelitySpider(),[]);
  const dissBreak=useMemo(()=>gDissipationBreakdown(),[]);
  return(<>
    <div style={{display:"flex",gap:5,marginBottom:14,flexWrap:"wrap"}}>{AZ_TABS.map(t=><Pill key={t.key} active={ws===t.key} label={t.label} onClick={()=>setWs(t.key)} color={C.cy}/>)}</div>
    <FadeSlide keyVal={ws}>
    {ws==="overlay"&&(<div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:12}}>
        <Sec title="Speed"><GC><ResponsiveContainer width="100%" height={200}><AreaChart data={track} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="speed" stroke={C.cy} fill={C.cy} fillOpacity={.1} strokeWidth={1.5} name="m/s"/></AreaChart></ResponsiveContainer></GC></Sec>
        <Sec title="Lat G"><GC><ResponsiveContainer width="100%" height={200}><AreaChart data={track} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="lat_g" stroke={C.am} fill={C.am} fillOpacity={.1} strokeWidth={1.5} name="G"/><ReferenceLine y={0} stroke={C.dm} strokeDasharray="3 3"/></AreaChart></ResponsiveContainer></GC></Sec>
        <Sec title="Curvature"><GC><ResponsiveContainer width="100%" height={200}><LineChart data={track} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Line type="monotone" dataKey="curvature" stroke={C.pr} strokeWidth={1.5} dot={false} name="κ"/></LineChart></ResponsiveContainer></GC></Sec>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
        <Sec title="Lap Delta"><GC><ResponsiveContainer width="100%" height={220}><ComposedChart data={lapDelta} margin={{top:8,right:16,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis yAxisId="l" {...AX}/><YAxis yAxisId="r" orientation="right" {...AX}/><Tooltip contentStyle={TT}/><Area yAxisId="l" type="monotone" dataKey="delta" stroke={C.red} fill={C.red} fillOpacity={.08} strokeWidth={2} name="Δt"/><Line yAxisId="r" type="monotone" dataKey="vActual" stroke={C.cy} strokeWidth={1} dot={false} name="v_act"/><Line yAxisId="r" type="monotone" dataKey="vOptimal" stroke={C.gn} strokeWidth={1} dot={false} name="v_opt" strokeDasharray="4 2"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></ComposedChart></ResponsiveContainer></GC></Sec>
        <Sec title="Grip Utilisation"><GC><ResponsiveContainer width="100%" height={220}><AreaChart data={gripUtil} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX} domain={[0,1.1]}/><Tooltip contentStyle={TT}/><ReferenceArea y1={.85} y2={1} fill={C.gn} fillOpacity={.04}/><ReferenceLine y={1} stroke={C.red} strokeDasharray="4 2"/><Area type="monotone" dataKey="utilisation" stroke={C.am} fill={C.am} fillOpacity={.12} strokeWidth={1.5} name="μ util"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:10}}>
        <Sec title="Driver Inputs"><GC><ResponsiveContainer width="100%" height={200}><LineChart data={driverIn} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Line type="monotone" dataKey="steerAct" stroke={C.cy} strokeWidth={1.5} dot={false} name="Steer Act"/><Line type="monotone" dataKey="steerOpt" stroke={C.cy} strokeWidth={1} dot={false} name="Steer Opt" strokeDasharray="4 2"/><Line type="monotone" dataKey="thrAct" stroke={C.gn} strokeWidth={1} dot={false} name="Thr%"/><Line type="monotone" dataKey="brkAct" stroke={C.red} strokeWidth={1} dot={false} name="Brk%"/><Legend wrapperStyle={{fontSize:7,fontFamily:C.hd}}/></LineChart></ResponsiveContainer></GC></Sec>
        <Sec title="Control Effort"><GC><ResponsiveContainer width="100%" height={200}><AreaChart data={ctrlEff} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis domain={[0,1]} {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="steerUtil" stroke={C.pr} fill={C.pr} fillOpacity={.08} strokeWidth={1.5} name="Steer"/><Area type="monotone" dataKey="brakeUtil" stroke={C.red} fill={C.red} fillOpacity={.08} strokeWidth={1.5} name="Brake"/><Area type="monotone" dataKey="throttleUtil" stroke={C.gn} fill={C.gn} fillOpacity={.08} strokeWidth={1.5} name="Throttle"/><Legend wrapperStyle={{fontSize:7,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
      </div>
    </div>)}
    {ws==="tubes"&&(<div style={{display:"grid",gridTemplateColumns:"1.2fr 1fr",gap:12}}>
      <Sec title="Track + Stochastic Tubes"><GC style={{padding:8}}><TubeTrackMap track={track} tubes={tubes} step={track.length-1} width={480} height={340}/></GC></Sec>
      <Sec title="Thermal Evolution — FL"><GC><ResponsiveContainer width="100%" height={340}><LineChart data={thermal5.filter((_,i)=>i%3===0)} margin={{top:8,right:16,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX} domain={[20,165]}/><Tooltip contentStyle={TT}/><ReferenceArea y1={85} y2={105} fill={C.gn} fillOpacity={.04}/><ReferenceLine y={140} stroke={C.red} strokeDasharray="4 2"/>{[["Flash",0,C.th_crit,"4 2"],["Surface",1,C.th_hot,""],["Bulk",2,C.th_warm,""],["Carcass",3,C.th_cool,""],["Gas",4,C.th_cold,""]].map(([n,idx,c,da])=><Line key={n} type="monotone" dataKey={d=>d.fl?.[idx]} stroke={c} strokeWidth={idx===1?2.5:1.5} dot={false} name={n} strokeDasharray={da}/>)}<Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></LineChart></ResponsiveContainer></GC></Sec>
      <Sec title="dH/dt"><GC><ResponsiveContainer width="100%" height={200}><ComposedChart data={energy.filter((_,i)=>i%3===0)} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="t" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><ReferenceArea y1={0} y2={50} fill={C.red} fillOpacity={.03}/><ReferenceArea y1={-50} y2={0} fill={C.gn} fillOpacity={.03}/><ReferenceLine y={0} stroke={C.gn} strokeDasharray="3 3"/><Line type="monotone" dataKey="dH" stroke={C.cy} strokeWidth={1.5} dot={false} name="dH/dt"/><Line type="monotone" dataKey="r_diss" stroke={C.e_diss} strokeWidth={1} dot={false} name="R_diss"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></ComposedChart></ResponsiveContainer></GC></Sec>
      <Sec title="AL Convergence"><GC><ResponsiveContainer width="100%" height={200}><AreaChart data={alData} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="solve" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/>{[["grip",C.red],["steer",C.am],["ax",C.cy],["track",C.gn],["vx",C.pr]].map(([k,c])=><Area key={k} type="monotone" dataKey={k} stackId="1" fill={c} fillOpacity={.2} stroke={c} strokeWidth={1} name={k}/>)}<Legend wrapperStyle={{fontSize:7,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
    </div>)}
    {ws==="spatial"&&(<div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
      <Sec title="Understeer Gradient"><GC><ResponsiveContainer width="100%" height={240}><ComposedChart data={understeer} margin={{top:8,right:16,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><ReferenceArea y1={0} y2={5} fill={C.red} fillOpacity={.03}/><ReferenceArea y1={-5} y2={0} fill={C.cy} fillOpacity={.03}/><ReferenceLine y={0} stroke={C.dm} strokeDasharray="3 3"/><Line type="monotone" dataKey="Ku" stroke={C.am} strokeWidth={1.5} dot={false} name="Ku×100"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></ComposedChart></ResponsiveContainer></GC></Sec>
      <Sec title="Yaw Phase Lag"><GC><ResponsiveContainer width="100%" height={240}><LineChart data={yawLag} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Line type="monotone" dataKey="lagMs" stroke={C.cy} strokeWidth={2} dot={false} name="Lag (ms)"/><ReferenceLine y={25} stroke={C.am} strokeDasharray="4 2"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></LineChart></ResponsiveContainer></GC></Sec>
    </div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:10}}>
      <Sec title="Roll Center Migration"><GC><ResponsiveContainer width="100%" height={220}><ScatterChart margin={{top:8,right:16,bottom:20,left:12}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="rcXf" name="X" {...AX}/><YAxis dataKey="rcYf" name="Y" {...AX}/><Tooltip contentStyle={TT}/><Scatter data={rcMig} name="Front RC">{rcMig.map((_,i)=><Cell key={i} fill={C.cy} opacity={.3+.7*(i/rcMig.length)}/>)}</Scatter></ScatterChart></ResponsiveContainer></GC></Sec>
      <Sec title="Ride Height Histogram"><GC><ResponsiveContainer width="100%" height={220}><BarChart data={rideH} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="height" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Bar dataKey="front" fill={C.cy} fillOpacity={.4} name="Front" radius={[2,2,0,0]}/><Bar dataKey="rear" fill={C.am} fillOpacity={.4} name="Rear" radius={[2,2,0,0]}/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></BarChart></ResponsiveContainer></GC></Sec>
    </div></div>)}
    {ws==="frequency"&&(<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
      <Sec title="Heave Frequency Response"><GC><ResponsiveContainer width="100%" height={260}><LineChart data={freqResp} margin={{top:8,right:16,bottom:20,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="freq" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Line type="monotone" dataKey="front_dB" stroke={C.cy} strokeWidth={2} dot={false} name="Front"/><Line type="monotone" dataKey="rear_dB" stroke={C.am} strokeWidth={2} dot={false} name="Rear"/><ReferenceLine y={0} stroke={C.dm} strokeDasharray="3 3"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></LineChart></ResponsiveContainer></GC></Sec>
      <Sec title="PSD Overlay"><GC><ResponsiveContainer width="100%" height={260}><LineChart data={psd} margin={{top:8,right:16,bottom:20,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="freq" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Line type="monotone" dataKey="real" stroke={C.am} strokeWidth={1.5} dot={false} name="Real"/><Line type="monotone" dataKey="sim" stroke={C.cy} strokeWidth={1.5} dot={false} name="Sim" strokeDasharray="4 2"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></LineChart></ResponsiveContainer></GC></Sec>
      <Sec title="Damper Velocity Histogram"><GC><ResponsiveContainer width="100%" height={240}><BarChart data={damperH} margin={{top:8,right:12,bottom:20,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="vel" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Bar dataKey="front" fill={C.cy} fillOpacity={.5} name="Front" radius={[2,2,0,0]}/><Bar dataKey="rear" fill={C.am} fillOpacity={.5} name="Rear" radius={[2,2,0,0]}/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></BarChart></ResponsiveContainer></GC></Sec>
      <Sec title="AL Slack"><GC><ResponsiveContainer width="100%" height={240}><AreaChart data={alSlack} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="slackGrip" stroke={C.red} fill={C.red} fillOpacity={.08} strokeWidth={1.5} name="Grip"/><Area type="monotone" dataKey="slackSteer" stroke={C.am} fill={C.am} fillOpacity={.06} strokeWidth={1.2} name="Steer"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
    </div>)}
    {ws==="fidelity"&&(<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
      <Sec title="EKF Residuals"><GC><ResponsiveContainer width="100%" height={260}><LineChart data={ekf.filter((_,i)=>i%2===0)} margin={{top:8,right:16,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="t" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><ReferenceLine y={0} stroke={C.gn} strokeDasharray="3 3"/><ReferenceArea y1={-.02} y2={.02} fill={C.gn} fillOpacity={.04}/><Line type="monotone" dataKey="innov_ax" stroke={C.cy} strokeWidth={1} dot={false} name="a_x"/><Line type="monotone" dataKey="innov_wz" stroke={C.am} strokeWidth={1} dot={false} name="ω_z"/><Line type="monotone" dataKey="innov_vy" stroke={C.pr} strokeWidth={1} dot={false} name="v_y"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></LineChart></ResponsiveContainer></GC></Sec>
      <Sec title="Pacejka Drift"><GC><ResponsiveContainer width="100%" height={260}><ComposedChart data={pacDrift} margin={{top:8,right:16,bottom:20,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="lap" {...AX}/><YAxis yAxisId="l" {...AX}/><YAxis yAxisId="r" orientation="right" {...AX}/><Tooltip contentStyle={TT}/><Line yAxisId="l" type="monotone" dataKey="muY_pct" stroke={C.am} strokeWidth={2} dot={{r:3,fill:C.am}} name="μ_y%"/><Line yAxisId="r" type="monotone" dataKey="stiffness" stroke={C.cy} strokeWidth={1.5} dot={false} name="C_α"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></ComposedChart></ResponsiveContainer></GC></Sec>
      <Sec title="Friction Saturation"><GC><ResponsiveContainer width="100%" height={220}><BarChart data={fricSat} margin={{top:8,right:12,bottom:20,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="bin" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Bar dataKey="count" name="Samples" radius={[2,2,0,0]}>{fricSat.map((e,i)=><Cell key={i} fill={e.bin>.85?C.red:e.bin>.6?C.am:C.gn} fillOpacity={.6}/>)}</Bar></BarChart></ResponsiveContainer></GC></Sec>
      <Sec title="Fidelity Scores"><GC><ResponsiveContainer width="100%" height={220}><BarChart data={fidelity} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="axis" {...AX} tick={{fontSize:7}}/><YAxis {...AX} domain={[0,100]}/><Tooltip contentStyle={TT}/><Bar dataKey="score" name="%" radius={[4,4,0,0]}>{fidelity.map((e,i)=><Cell key={i} fill={e.score>90?C.gn:e.score>80?C.am:C.red} fillOpacity={.6}/>)}</Bar></BarChart></ResponsiveContainer></GC></Sec>
    </div>)}
    {ws==="contact"&&(<div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
        <Sec title="Load Transfer (Fz)"><GC><ResponsiveContainer width="100%" height={240}><LineChart data={loadTrans.filter((_,i)=>i%3===0)} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Line type="monotone" dataKey="Fz_fl" stroke={C.cy} strokeWidth={1.5} dot={false} name="FL"/><Line type="monotone" dataKey="Fz_fr" stroke={C.am} strokeWidth={1.5} dot={false} name="FR"/><Line type="monotone" dataKey="Fz_rl" stroke={C.gn} strokeWidth={1} dot={false} name="RL" strokeDasharray="4 2"/><Line type="monotone" dataKey="Fz_rr" stroke={C.pr} strokeWidth={1} dot={false} name="RR" strokeDasharray="4 2"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></LineChart></ResponsiveContainer></GC></Sec>
        <Sec title="Slip Energy"><GC><ResponsiveContainer width="100%" height={240}><AreaChart data={slipE.filter((_,i)=>i%3===0)} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="energy" stroke={C.red} fill={C.red} fillOpacity={.12} strokeWidth={1.5} name="kJ"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:10}}>
        <Sec title="Hamiltonian Energy"><GC><ResponsiveContainer width="100%" height={220}><AreaChart data={hamilE} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="s" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="kinetic" stackId="1" fill={C.e_ke} fillOpacity={.25} stroke={C.e_ke} strokeWidth={1} name="KE"/><Area type="monotone" dataKey="potential" stackId="1" fill={C.e_spe} fillOpacity={.25} stroke={C.e_spe} strokeWidth={1} name="PE"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
        <Sec title="Dissipation Breakdown"><GC><ResponsiveContainer width="100%" height={220}><BarChart data={dissBreak} layout="vertical" margin={{top:8,right:16,bottom:8,left:80}}><CartesianGrid strokeDasharray="3 3" stroke={GS} horizontal={false}/><XAxis type="number" {...AX}/><YAxis dataKey="component" type="category" tick={{fontSize:8,fill:C.br,fontFamily:C.dt}} stroke={C.b1} width={75}/><Tooltip contentStyle={TT}/><Bar dataKey="energy" name="J" radius={[0,4,4,0]} barSize={14}>{dissBreak.map((e,i)=><Cell key={i} fill={e.color} fillOpacity={.7}/>)}</Bar></BarChart></ResponsiveContainer></GC></Sec>
      </div>
    </div>)}
    {ws==="ai"&&(<div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:12}}>
        <Sec title="MPC Horizon"><GC><ResponsiveContainer width="100%" height={240}><ComposedChart data={horizon} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="xPred" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="yBoundL" stroke="none" fill={C.gn} fillOpacity={.06} name="Track L"/><Area type="monotone" dataKey="yBoundR" stroke="none" fill={C.gn} fillOpacity={.06} name="Track R"/><Line type="monotone" dataKey="yPred" stroke={C.cy} strokeWidth={2} dot={false} name="Predicted Y"/><Legend wrapperStyle={{fontSize:7,fontFamily:C.hd}}/></ComposedChart></ResponsiveContainer></GC></Sec>
        <Sec title="UT σ Growth"><GC><ResponsiveContainer width="100%" height={240}><AreaChart data={horizon} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="step" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="sigma" stroke={C.pr} fill={C.pr} fillOpacity={.15} strokeWidth={2} name="σ (m)"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
        <Sec title="Wavelet Coefficients"><GC><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4}}>{["cA3","cD3","cD2","cD1"].map(lv=>{const ld=wavCoeffs.filter(d=>d.level===lv);return(<div key={lv}><span style={{fontSize:8,fontWeight:700,color:lv==="cA3"?C.cy:C.am,fontFamily:C.dt,letterSpacing:1.5,textTransform:"uppercase"}}>{lv}</span><div style={{display:"flex",gap:1,marginTop:4,flexWrap:"wrap"}}>{ld.map((w,i)=><div key={i} style={{width:12,height:12,borderRadius:2,background:w.active?lv==="cA3"?C.cy:C.am:C.b1,opacity:.3+w.mag*.7}} title={`${w.mag.toFixed(3)}`}/>)}</div></div>);})}</div></GC></Sec>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
        <Sec title="Energy Budget"><GC><ResponsiveContainer width="100%" height={220}><AreaChart data={energy.filter((_,i)=>i%3===0)} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="t" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Area type="monotone" dataKey="ke" stackId="1" fill={C.e_ke} fillOpacity={.25} stroke={C.e_ke} strokeWidth={1} name="KE"/><Area type="monotone" dataKey="pe_s" stackId="1" fill={C.e_spe} fillOpacity={.2} stroke={C.e_spe} strokeWidth={1} name="PE_s"/><Area type="monotone" dataKey="h_net" stackId="1" fill={C.e_hnet} fillOpacity={.3} stroke={C.e_hnet} strokeWidth={1.5} name="H_net"/><Legend wrapperStyle={{fontSize:7,fontFamily:C.hd}}/></AreaChart></ResponsiveContainer></GC></Sec>
        <Sec title="H_net + R_diss"><GC><ResponsiveContainer width="100%" height={220}><ComposedChart data={energy.filter((_,i)=>i%3===0)} margin={{top:8,right:12,bottom:8,left:8}}><CartesianGrid strokeDasharray="3 3" stroke={GS}/><XAxis dataKey="t" {...AX}/><YAxis {...AX}/><Tooltip contentStyle={TT}/><Line type="monotone" dataKey="h_net" stroke={C.e_hnet} strokeWidth={2} dot={false} name="H_net (J)"/><Line type="monotone" dataKey="r_diss" stroke={C.e_diss} strokeWidth={1.5} dot={false} name="R_diss (W)"/><ReferenceLine y={0} stroke={C.dm} strokeDasharray="3 3"/><Legend wrapperStyle={{fontSize:8,fontFamily:C.hd}}/></ComposedChart></ResponsiveContainer></GC></Sec>
      </div>
    </div>)}
    </FadeSlide>
  </>);
}

// ═════════════════════════════════════════════════════════════════════════════
export default function TelemetryModule({track,tireTemps,mode,thermal5=[],tubes=[],wavelets=[],alData=[],energy=[]}){
  if(mode==="LIVE")return<LiveMode mode={mode} thermal5={thermal5} tubes={tubes} wavelets={wavelets} alData={alData} energy={energy} track={track}/>;
  return<AnalyzeMode track={track} tireTemps={tireTemps} thermal5={thermal5} tubes={tubes} energy={energy} alData={alData}/>;
}